"""Generates -- but never executes -- the exact commands an operator needs around a prepared
full-corpus run (brief §11): the real launch command, plus dashboard/log-follow/status/stop/resume/
post-first-shard/post-first-epoch commands. `prepare` writes these to a clearly marked
`LAUNCH_COMMANDS.txt` file (`# DO NOT EXECUTE AUTOMATICALLY` banner) and the same strings are printed
in the final CLI report -- one source of truth for both.

**No persisted stdout log file exists in this architecture** (confirmed by reading
`container_epoch_runner.py`: the container's own `log.csv` lives inside its per-epoch output
directory, never streamed to one durable run-level log). "Log following" here is therefore an honest
polling loop over the real `status` command and `session_state.json`, not a `tail -f` over a file that
does not exist.
"""

from __future__ import annotations

import sys
from pathlib import Path

from pydantic import BaseModel, ConfigDict

DO_NOT_EXECUTE_BANNER = "# DO NOT EXECUTE AUTOMATICALLY -- this file documents commands for the operator to run manually."


class LaunchPreview(BaseModel):
    model_config = ConfigDict(frozen=True)

    launch_command: str
    dashboard_command: str
    status_command: str
    log_follow_command: str
    safe_interrupt_command: str
    resume_command_template: str
    post_first_shard_inspection_command: str
    post_first_epoch_validation_command: str


def _python() -> str:
    return sys.executable or "python"


def build_launch_preview(
    *, run_dir: str | Path, hours: float = 5.0, batch_size: int = 16,
) -> LaunchPreview:
    run_dir = Path(run_dir)
    python = _python()
    module = "archivetrust.htr.training.full_run"

    launch_command = (
        f'{python} -m {module} start --run "{run_dir}" --hours {hours} --batch-size {batch_size} '
        "--confirm-full-corpus-run"
    )
    dashboard_command = f'{python} -m {module} gui'
    status_command = f'{python} -m {module} status --run "{run_dir}"'
    log_follow_command = (
        f'powershell -Command "while ($true) {{ {python} -m {module} status --run \\"{run_dir}\\"; '
        'Start-Sleep -Seconds 30 }" '
        "  (no persisted stdout log file exists in this architecture -- this polls the real "
        "run_state.json/session_state.json on an interval instead of tailing a file)"
    )
    safe_interrupt_command = f'{python} -m {module} stop --run "{run_dir}"'
    resume_command_template = (
        f'{python} -m {module} resume --run "{run_dir}" --hours <HOURS> --batch-size {batch_size} '
        "  (usable once run_state.json exists with a status other than 'prepared'; no checkpoint "
        "exists yet on a freshly prepared run, so this is a template, not yet a runnable command)"
    )
    post_first_shard_inspection_command = (
        f'{python} -m {module} status --run "{run_dir}"'
        "  (after shard 1 completes: check current_epoch == 1, latest_checkpoint is set, "
        "latest_metrics is populated)"
    )
    post_first_epoch_validation_command = (
        f'{python} -c "from archivetrust.htr.training.training_session import load_session_state; '
        f's = load_session_state(r\'{run_dir / "run-state"}\'); print(s.validation_history[-1] if s and s.validation_history else None)"'
        "  (confirms a real validation pass, not just a training step, ran on shard 1)"
    )

    return LaunchPreview(
        launch_command=launch_command,
        dashboard_command=dashboard_command,
        status_command=status_command,
        log_follow_command=log_follow_command,
        safe_interrupt_command=safe_interrupt_command,
        resume_command_template=resume_command_template,
        post_first_shard_inspection_command=post_first_shard_inspection_command,
        post_first_epoch_validation_command=post_first_epoch_validation_command,
    )


def write_launch_preview_file(preview: LaunchPreview, output_path: str | Path) -> None:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        DO_NOT_EXECUTE_BANNER,
        "#",
        "# This file was generated by `prepare`. Nothing in this codebase ever executes these",
        "# commands automatically. Running the launch command below is the one, explicit, manual",
        "# action that starts real full-corpus training.",
        "",
        "## Launch (starts real full-corpus training -- run this manually when ready)",
        preview.launch_command,
        "",
        "## Dashboard",
        preview.dashboard_command,
        "",
        "## Status",
        preview.status_command,
        "",
        "## Log following (polling -- see module docstring)",
        preview.log_follow_command,
        "",
        "## Safe graceful interrupt",
        preview.safe_interrupt_command,
        "",
        "## Resume (template -- fill in --hours once a checkpoint exists)",
        preview.resume_command_template,
        "",
        "## Post-first-shard inspection",
        preview.post_first_shard_inspection_command,
        "",
        "## Post-first-epoch validation check",
        preview.post_first_epoch_validation_command,
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="utf-8")
